add_newline = false
command_timeout = 1000

format = """
$directory\
$time\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character
"""

right_format = """
$golang\
$python\
$ruby\
$aws\
$kubernetes\
$terraform
"""

[aws]
format = '([$symbol($profile)(\($region\))]($style))'
style = "bold cyan"
force_display = true

[aws.region_aliases]
eu-central-1 = ""

[directory]
style = "#1E90FF"
repo_root_style = "bold #0000FF"
truncation_length = 6

[character]
success_symbol = "[‚ùØ](green)"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold #8A2BE2"
truncation_length = 30

[git_status]
format = "([$all_status$ahead_behind]($style))"
conflicted = "[!](#DC143C) "
ahead = "‚á° "
behind = "‚á£ "
diverged = "‚áï "
untracked = '[?\($count\)](#DC143C) '
stashed = '[\$](#0000FF) '
modified = '[*\($count\)](#DC143C) '
staged = '[+\($count\)](green) '
renamed = '[¬ª\($count\)](green) '
deleted = '[‚úò\($count\)](#DC143C) '

[golang]
format = "[$symbol($version )]($style)"
version_format = "${raw}"

[kubernetes]
disabled = false
format = '[ $symbol$context( \($namespace\))]($style)'
style = "bold #FFCC99"

[kubernetes.context_aliases]
'arn:.*:cluster/(?P<cluster>[\w-]+)' = "$cluster"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "${raw}"

[ruby]
format = "[$symbol($version )]($style)"
symbol = "üî∫ "
version_format = "${raw}"

[terraform]
format = " [$symbol$workspace]($style)"
detect_extensions = ["tf", "tfplan", "tfstate", "hcl"]

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M "
style ="#95A5A6 dimmed"
