add_newline = false
command_timeout = 1000

format = """
$directory\
$time\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character
"""

right_format = """
$golang\
$python\
$ruby\
$aws\
$kubernetes\
$terraform
"""

[aws]
force_display = true
format = '([$symbol($profile)(\($region\))]($style))'
style = "bold #ffb86c"

[aws.region_aliases]
eu-central-1 = ""

[directory]
style = "bold #50fa7b"
truncation_length = 6

[character]
error_symbol = "[‚ùØ](bold #ff5555)"
success_symbol = "[‚ùØ](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold #ff79c6"
truncation_length = 30

[git_status]
ahead = "‚á° "
behind = "‚á£ "
conflicted = "[!](#ff5555) "
deleted = '[‚úò\($count\)](#ff5555) '
diverged = "‚áï "
format = "([$all_status$ahead_behind]($style))"
modified = '[*\($count\)](#ff5555) '
renamed = '[¬ª\($count\)](#50fa7b) '
staged = '[+\($count\)](#50fa7b) '
stashed = '[\$](#8be9fd) '
untracked = '[?\($count\)](#bd93f9) '

[golang]
format = "[$symbol($version )]($style)"
version_format = "${raw}"

[kubernetes]
disabled = false
format = '[ $symbol$context( \($namespace\))]($style)'
style = "bold #f1fa8c"

[kubernetes.context_aliases]
'arn:.*:cluster/(?P<cluster>[\w-]+)' = "$cluster"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "${raw}"

[ruby]
format = "[$symbol($version )]($style)"
symbol = "üî∫ "
version_format = "${raw}"

[terraform]
detect_extensions = ["tf", "tfplan", "tfstate", "hcl"]
format = " [$symbol$workspace]($style)"
style = "bold #8be9fd"

[time]
disabled = false
format = "[$time]($style)"
style = "#6272a4"
time_format = "%H:%M "
